### ISSUE TITLE
Create a new help/ directory and move the ldac_help.md file in there as index.md

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/ro-crate-modes#17]
Break out the specific instuctions for editing language metadata and schemas into their own files:

help/modes/language-data-commons.md
help/modes/schema.md

(We'll add a new element in the Mode file for mode specific help)

**Comment by rosanna-smith** [comment]
Separated into three files now:
General help - Crate-O: https://github.com/Language-Research-Technology/crate-o/blob/help_docs/help/index.md
Language Data Commons: https://github.com/Language-Research-Technology/ro-crate-editor-profiles/blob/help_docs/help/modes/language-data-commons.md
Schema: https://github.com/Language-Research-Technology/ro-crate-editor-profiles/blob/help_docs/help/modes/schema.md
