### ISSUE TITLE
s/profile/mode/gi

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/ro-crate-modes#20]
Change the name of this repo to 

ro-crate-modes

and change all references to profile (in the sense of crate-o config) to mode

NOTE that lib/profile.js should NOT change -- this generates profile documentation from a mode file maybe this should go to ro-crate schema tools???

**Comment by rosanna-smith** [comment]
@ptsefton Question for this one, should I fork this first and work on a new branch, or just create a new branch for these changes without forking?

**Comment by ptsefton** [comment]
Create a new branch and at some point we'll change the name of the repo -- you can either work on the branch here, or fork and do pull requests as you like

**Comment by rosanna-smith** [comment]
Updates made to the help_docs branch of ro-crate-editor-profiles, now over to @alvinsw for review in case other areas should be renamed as well. There are some instances of mode file vs mode that we might want to update as well but leaving them at the moment for the full context.

**Comment by rosanna-smith** [comment]
Reviewed by Alvin and merged back to main. Over to @moisbo to change the repo name to ro-crate-modes
