### ISSUE TITLE
Enforce the existence of certain entity types

### ISSUE THREAD

**Issue by multimeric** [Language-Research-Technology/ro-crate-modes#38]
My profile introduces some new entities, but it makes little sense for someone to use my profile without using any of them. They also aren't directly linked to the root `Dataset` entity, so I can't use `required: true` to solve this. Therefore, it would be nice to be able to enforce the existence of certain entities.

Incidentally, it seems that SHACL can do this with [`sh:minCount`](https://www.w3.org/TR/shacl/#MinCountConstraintComponent), which might incentivise SHACL validation (potentially via LinkML).

**Comment by ptsefton** [comment]
Can you give a concrete example?

**Comment by multimeric** [comment]
Sure, so let's say I was creating a Single Cell Transcriptomics profile, which roughly aligns with the [minSCE standard](https://pmc.ncbi.nlm.nih.gov/articles/PMC9302581/). One of the entities that I define will probably be the single cell isolation protocol, which will have the type `IsolationProtocol`. Therefore to conform to my profile, there must be an entity in the crate with `"type": ["bioschemas/LabProtocol", "IsolationProtocol"]`. Otherwise, a user could submit a metadata file that describes all the files in the crate but neglects to add any single cell specific metadata.

**Comment by ptsefton** [comment]
This is a big complicated issue -- I get the requirement you're expressing but I think that in the use case you have if something is important to have, then it should be linked explicitly from the Root with only one or two hops using an appropriate property such as `hasProtocol` -- the problem I ran into looking into this though is that Bioschemas does not actually publish their full schema -- they only have the Types/Classes, and no independent definitions of properties so it's hard to work out what property might have the range `LabProtocol`.

Another issue to consider is whether you really want to be making up new Classes for stuff like IsolationProtocol, or use a lighter-weight method by defining a set of DefinedTerms  and use a property like `protocolType` pointing to these terms -- this is the approach we took in the Language Schema work.

I think that what you're trying to do is acutally a job for a working group but a good starting point would be to sit down and hand-code some example RO-Crates and see how they look using a generic RO-Crate HTML preview, THEN design the schema and profile, and seek a broader community to consult with.

**Comment by multimeric** [comment]
> then it should be linked explicitly from the Root with only one or two hops using an appropriate property such as hasProtocol

I can do this as a stopgap solution , although I don't think this is ideal. For example, if I give a dataset a protocol, then a conformant crate can no longer handle multiple sets of sample with different isolation profiles.

> Another issue to consider is whether you really want to be making up new Classes for stuff like IsolationProtocol, or use a lighter-weight method by defining a set of DefinedTerms and use a property like protocolType pointing to these terms

I think I would rather create new entities because the standards I'm converting generally use this model. In any case, even if I add a `protocolType`, won't it need to point to a custom entity?

> I think that what you're trying to do is acutally a job for a working group but a good starting point would be to sit down and hand-code some example RO-Crates and see how they look using a generic RO-Crate HTML preview, THEN design the schema and profile, and seek a broader community to consult with.

Ideally yes, but the schemas themselves have already been designed via a working group. I'm not really designing schemas so much as converting those to RO-Crate compatible forms.
